--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: future_core_planning; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.future_core_planning (
    id integer NOT NULL,
    regcd bigint,
    cpn character varying(200) DEFAULT NULL::character varying,
    coreg character varying(200) DEFAULT NULL::character varying,
    fcoreg character varying(200) DEFAULT NULL::character varying,
    code character varying(30) NOT NULL,
    name character varying(30) DEFAULT NULL::character varying,
    updt character varying(200) DEFAULT NULL::character varying,
    effdt timestamp with time zone,
    stat character varying(200) DEFAULT NULL::character varying,
    updated_by character varying(250) DEFAULT NULL::character varying NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    validationstatus character varying(250) DEFAULT NULL::character varying,
    is_valid boolean NOT NULL,
    created_date timestamp with time zone,
    created_by character varying(50) DEFAULT NULL::character varying,
    comment character varying(250) DEFAULT NULL::character varying,
    fcc numeric(63,2),
    curcoc numeric(63,2)
);


ALTER TABLE public.future_core_planning OWNER TO postgres;

--
-- Name: future_core_planning_code_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.future_core_planning_code_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1;


ALTER SEQUENCE public.future_core_planning_code_seq OWNER TO postgres;

--
-- Name: future_core_planning_code_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.future_core_planning_code_seq OWNED BY public.future_core_planning.code;


--
-- Name: future_core_planning_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.future_core_planning ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.future_core_planning_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: future_core_planning code; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.future_core_planning ALTER COLUMN code SET DEFAULT nextval('public.future_core_planning_code_seq'::regclass);


--
-- Data for Name: future_core_planning; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.future_core_planning (id, regcd, cpn, coreg, fcoreg, code, name, updt, effdt, stat, updated_by, updated_date, validationstatus, is_valid, created_date, created_by, comment, fcc, curcoc) FROM stdin;
1	2	C4707QP	SC4707	SC4707	1	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.839738+00	ValidationSucceeded	t	2024-06-18 19:34:28.839738+00	\N	\N	20.00	18.00
2	2	XM3054	BC604	BC604	2	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.855171+00	ValidationSucceeded	t	2024-06-18 19:34:28.855171+00	\N	\N	400.00	300.00
3	2	XM3055	BC604	BC604	3	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.86955+00	ValidationSucceeded	t	2024-06-18 19:34:28.86955+00	\N	\N	400.00	300.00
4	2	C1308	SC4702	SC1308	4	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.883531+00	ValidationSucceeded	t	2024-06-18 19:34:28.883531+00	\N	\N	20.00	20.00
5	2	XM3087	BC605	BC604	5	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.897373+00	ValidationSucceeded	t	2024-06-18 19:34:28.897373+00	\N	\N	300.00	300.00
6	2	XM3088	BC605	BC605	6	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.911144+00	ValidationSucceeded	t	2024-06-18 19:34:28.911144+00	\N	\N	300.00	300.00
7	2	C4515F3	SC4515F3	SC0000	7	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.924977+00	ValidationSucceeded	t	2024-06-18 19:34:28.924977+00	\N	\N	15.00	12.00
8	2	C4707	BC609	BC609	8	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.93914+00	ValidationSucceeded	t	2024-06-18 19:34:28.93914+00	\N	\N	20.00	18.00
9	1	C4707QP	SC4707	SC4707	9	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.953074+00	ValidationSucceeded	t	2024-06-18 19:34:28.953074+00	\N	\N	20.00	18.00
10	1	XM3054	BC604	BC604	10	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.967214+00	ValidationSucceeded	t	2024-06-18 19:34:28.967214+00	\N	\N	400.00	300.00
11	1	XM3055	BC604	BC604	11	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.981545+00	ValidationSucceeded	t	2024-06-18 19:34:28.981545+00	\N	\N	400.00	300.00
12	1	C1308	SC4702	SC1308	12	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:28.995422+00	ValidationSucceeded	t	2024-06-18 19:34:28.995422+00	\N	\N	20.00	20.00
13	1	XM3087	BC605	BC604	13	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:29.008951+00	ValidationSucceeded	t	2024-06-18 19:34:29.008951+00	\N	\N	400.00	300.00
14	1	XM3088	BC605	BC605	14	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:29.022787+00	ValidationSucceeded	t	2024-06-18 19:34:29.022787+00	\N	\N	300.00	300.00
15	1	C4515F3	SC4515F3	SC0000	15	\N	ANAND	2024-06-19 00:00:00+00	A	system@spriced.com	2024-06-18 19:34:29.036443+00	ValidationSucceeded	t	2024-06-18 19:34:29.036443+00	\N	\N	15.00	12.00
16	1	C4707	BC609	BC609	16	\N	ANAND	2024-06-19 00:00:00+00	A	anand.kumar3@cummins.com	2024-06-18 19:35:28.850334+00	ValidationSucceeded	t	2024-06-18 19:34:29.050446+00	\N	\N	20.00	18.00
\.


--
-- Name: future_core_planning_code_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.future_core_planning_code_seq', 19, true);


--
-- Name: future_core_planning_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.future_core_planning_id_seq', 18, true);


--
-- Name: future_core_planning pk_future_core_planning.id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.future_core_planning
    ADD CONSTRAINT "pk_future_core_planning.id" PRIMARY KEY (id);


--
-- Name: future_core_planning uk_future_core_planning.code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.future_core_planning
    ADD CONSTRAINT "uk_future_core_planning.code" UNIQUE (code);


--
-- Name: future_core_planning uk_future_core_planning_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.future_core_planning
    ADD CONSTRAINT uk_future_core_planning_code UNIQUE (code);


--
-- Name: future_core_planning future_core_planning_before_insert_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER future_core_planning_before_insert_trigger BEFORE INSERT ON public.future_core_planning FOR EACH ROW EXECUTE FUNCTION public.future_core_planning_before_insert();


--
-- Name: future_core_planning future_core_planning_before_update_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER future_core_planning_before_update_trigger BEFORE UPDATE ON public.future_core_planning FOR EACH ROW EXECUTE FUNCTION public.future_core_planning_before_update();


--
-- Name: future_core_planning future_core_planning_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER future_core_planning_trigger AFTER INSERT OR UPDATE ON public.future_core_planning FOR EACH ROW EXECUTE FUNCTION public.history_trigger();


--
-- Name: future_core_planning trg_prevent_code_null; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_prevent_code_null BEFORE UPDATE ON public.future_core_planning FOR EACH ROW EXECUTE FUNCTION public.prevent_code_null();


--
-- Name: future_core_planning fk_future_core_planning_regcd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.future_core_planning
    ADD CONSTRAINT fk_future_core_planning_regcd FOREIGN KEY (regcd) REFERENCES public.p_pricing_region(id);


--
-- PostgreSQL database dump complete
--

