import requests
import csv

def fetch_data_from_api(api_endpoint, bearer_token):
    headers = {
        "Authorization": f"Bearer {bearer_token}"
    }
    response = requests.get(api_endpoint, headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Failed to fetch data from API")
        if response.status_code == 401:
            print(f"Apply proper Bearer token!, status code : {response.status_code}")
        else:
            print(f" status code : {response.status_code}")
        return None

def format_data_type(data_type):
    if data_type == "INTEGER" or data_type == "AUTO":
        return "numeric"
    elif data_type == "VARCHAR" or data_type == "TEXT":
        return "char"
    elif data_type == "TIMESTAMP" or data_type == "TIME_STAMP":
        return "datetime"
    elif "string_var" in data_type.lower():
        return "char"
    elif data_type == "auto":
        return "numeric"
    else:
        return data_type.lower()

def write_to_csv(data, filename):
    unique_tables = []
    related_table_data = []
    
    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['SPRICED_TABLE_NAME', 'Table_Display_Name', 'TABLE_SCHEMA', 'COLUMN_NAME', 'DISPLAY_NAME', 'DATA_TYPE', 'SIZE', 'POS', 'IS_NULLABLE', 'IS_REF_COLUMN', 'PRIMARY_KEY', 'AUTOGEN', 'Ref'])
        for entity in data:
            table_name = entity["name"]
            table_display_name = entity["displayName"] 
            entity_id = entity["id"]
            attributes = entity["attributes"]
            unique_tables.append((table_name, entity_id))
            for attribute in attributes:
                column_name = attribute["name"]
                if column_name.lower() in ['id', 'updated_date', 'comment', 'updated_by', 'is_valid', 'created_date', 'created_by', 'validationstatus']:
                    continue
                display_name = attribute["displayName"]
                data_type = format_data_type(attribute["dataType"])
                size = attribute.get("size", None)
                pos = attribute.get("numberOfDecimalValues", None)
                is_nullable = "no" if not attribute["nullable"] else "yes"
                is_ref_column = "TRUE" if attribute["type"] == "LOOKUP" else "FALSE"
                primary_key = ""
                if attribute["constraintType"] == "UNIQUE_KEY":
                    primary_key = "UK"
                elif attribute["constraintType"] == "FOREIGN_KEY":
                    primary_key = "FK"
                elif attribute["constraintType"] == "PRIMARY_KEY":
                    primary_key = "PK"
                autogen = "true" if attribute["autoGenerated"] else ""
                ref = attribute.get("referencedTable", "")
                
                writer.writerow([table_name, table_display_name, 'spriced', column_name, display_name, data_type, size, pos, is_nullable, is_ref_column, primary_key, autogen, ref])
                
                if ref:
                    related_table_data.append([table_name, column_name, display_name, ref])
    
    print(f"All table details written to -> {filename} ,successfully!")

    # Write related_table.csv
    with open('related_tables.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['entity_name', 'columns', 'display_name', 'linked_to'])
        for row in related_table_data:
            writer.writerow(row)
    
    print(f"All related table details written to -> related_tables.csv ,successfully!")

    # Sort the unique tables by entity_id
    sorted_unique_tables = sorted(unique_tables, key=lambda x: x[1])
    
    # Write sequence_tables.csv
    with open('sequence_tables.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['json_name', 'Sequence of Ingestion'])
        for table_name, entity_id in sorted_unique_tables:
            writer.writerow([table_name, entity_id])
    
    print(f"All unique table names written to -> sequence_tables.csv ,successfully!")

def main():
    api_endpoint = "https://spriced.meritor.uat.simadvisory.com/api/v1/definition/models/1/entities"
    bearer_token = ""  # Replace with your actual bearer token
    data = fetch_data_from_api(api_endpoint, bearer_token)
    if data:
        write_to_csv(data, "sourceDataGen.csv")
    else:
        print("No data fetched from the API.")

if __name__ == "__main__":
    main()
