-- View: public.temp_part_regional

-- DROP VIEW public.temp_part_regional;

CREATE OR REPLACE VIEW public.temp_part_regional AS
SELECT name AS "Name",
    brnd_cd AS "Brand Code",
    gbb AS "Good/Better/Best",
    lfcycle AS "Lifecycle Stage",
    mktcd AS "Market Code",
    mfgcc AS "Mfg. Class Code",
    prod_cd1 AS "Product Code - 1 Digit",
    prod_cd3 AS "Product Code - 3 Digit",
    mfgpdcd AS "Product Code (Mfg. Product Code)",
    prdmgr AS "Product Manager",
    part_num AS "Compressed Part Number",
    code AS "Code",
    long_ptno AS "Long Part Number",
    projcst AS "Projected Cost",
    prod_cd5 AS "Product Code - 5 Digit",
    cr_dt AS "Created Date",
    shrt_desc AS "Short Description",
    long_desc AS "Long Description",
    fran_code AS "Franchise Code",
    prtcls AS "Part Class",
    sup_prt AS "Supersecession (Part Replaced By)",
    prtstat AS "Part Status",
    popcdny AS "Pop Code - Next Year",
    popcdcy AS "Pop Code - Current Year",
    pllqty AS "Pallet Quantity",
    drop_ship AS "Drop Ship Only",
    cat_cd AS "Catalog Code",
    cc1 AS "Cc - 1-Digit Att",
    cc2 AS "Cc - 2-Digit Att",
    cc3 AS "Cc - 3-Digit Att",
    cc4 AS "Cc - 4-Digit Att",
    cc5 AS "Cc - 5-Digit Att",
    sac AS "Sales Activity Code",
    uac AS "Usage Activity Code",
    stdcst AS "Standard Cost",
    crcst AS "Core Cost",
    lprc AS "List Price",
    crprc AS "Core Price (Core Charge)",
    stdmcrcst AS "Standard Less Core Cost",
    lpp_prc AS "Last Price Paid - Price",
    lppqty AS "Last Price Paid - Qty",
    lppdt AS "Last Price Paid - Date",
    lppvndr AS "Last Price Paid - Vendor",
    postdt AS "Po Price - Start Date",
    poenddt AS "Po Price - End Date",
    povndr AS "Po Price - Vendor",
    pofgt AS "Po Price - Freight",
    popblp AS "Po Price- Price Break Level Price",
    popblq AS "Po Price- Price Break Level Qty",
    popt AS "Po Price - Purchase Type",
    pocurr AS "Po Price - Currency",
    pofdc AS "Po Price - Fdc",
    uytd AS "Usage Ytd (Qty)",
    uy1qty AS "Usage Y1 (Qty)",
    uy2qty AS "Usage Y2 (Qty)",
    uy3qty AS "Usage Y3 (Qty)",
    uy4qty AS "Usage Y4 (Qty)",
    uy5qty AS "Usage Y5 (Qty)",
    mfgnr AS "Mfg. New / Reman",
    mfgcommcd AS "Mfg. Commodity Code",
    mfgfamcd AS "Mfg. Family Code",
    pnf_fmsi AS "Mfg. Fmsi",
    mktcdl1 AS "Market Code Level 1",
    mktcdl2 AS "Market Code Level 2",
    mktcdl3 AS "Market Code Level 3",
    mktcdl4 AS "Market Code Level 4",
    mktcdl5 AS "Market Code Level 5",
    kit_flag AS "Kit Flag",
    cr_gp AS "Core Group",
    core_part AS "Core Part",
    origin AS "Country Of Origin",
    nonrtn AS "Eligible For Return",
    harcode AS "Harmonizing Code",
    ldtime AS "Sales Lead Time",
    upc AS "Upc",
    vmrs AS "Vmrs",
    height AS "Height",
    prtlen AS "Length",
    prtwid AS "Width",
    planner AS "Planner",
    buyer AS "Buyer",
    cystdmtl AS "Current Year Standard Material Cost",
    dutfrgexc AS "Duty & Freight Are Excluded",
    dutycst AS "Duty Cost",
    frgtcst AS "Freight Cost",
    mfglabcst AS "Mfg. Labor Cost",
    whburcst AS "Whse Burden Cost",
    mfgbcst AS "Mfg. Burden Cost",
    warbcst AS "Warranty Burden Cost",
    pckcst AS "Packaging Cost",
    corqty AS "Core Part Quantity",
    vndrnm AS "Vendor Name",
    vndrcd AS "Vendor Code",
    rgcd AS "Region Code",
    sub_brand AS "Sub Brand",
    part_uofm AS "Unit of Measure",
    rg_part,
    cbseg AS "Customer Business Segment",
    sup_dt AS "Supersession Date",
    id,
    updated_by AS "Updated By",
    updated_date AS "Last Updated On",
    validationstatus AS "Validation Status",
    is_valid AS "Is Valid",
    created_date AS "Created On",
    created_by AS "Created By",
    comment AS "Annotation"
   FROM part_regional;;

ALTER TABLE public.temp_part_regional
    OWNER TO postgres;