-- View: public.view_part_regional

-- DROP VIEW public.view_part_regional;

CREATE OR REPLACE VIEW public.view_part_regional AS
SELECT part_regional.name,
    x_brand_brnd_cd.id AS brnd_cd,
    x_brand_brnd_cd.name AS brnd_cd_name,
    x_brand_brnd_cd.code AS brnd_cd_code,
    x_good_better_best_gbb.id AS gbb,
    x_good_better_best_gbb.name AS gbb_name,
    x_good_better_best_gbb.code AS gbb_code,
    x_lifecycle_stage_lfcycle.id AS lfcycle,
    x_lifecycle_stage_lfcycle.name AS lfcycle_name,
    x_lifecycle_stage_lfcycle.code AS lfcycle_code,
    part_regional.mktcd,
    x_mfg_prod_code_class_mfgcc.id AS mfgcc,
    x_mfg_prod_code_class_mfgcc.name AS mfgcc_name,
    x_mfg_prod_code_class_mfgcc.code AS mfgcc_code,
    x_product_code_1_digit_prod_cd1.id AS prod_cd1,
    x_product_code_1_digit_prod_cd1.name AS prod_cd1_name,
    x_product_code_1_digit_prod_cd1.code AS prod_cd1_code,
    x_product_code_3_digit_prod_cd3.id AS prod_cd3,
    x_product_code_3_digit_prod_cd3.name AS prod_cd3_name,
    x_product_code_3_digit_prod_cd3.code AS prod_cd3_code,
    x_mfg_prod_code_mfgpdcd.id AS mfgpdcd,
    x_mfg_prod_code_mfgpdcd.name AS mfgpdcd_name,
    x_mfg_prod_code_mfgpdcd.code AS mfgpdcd_code,
    org_chart_prdmgr.id AS prdmgr,
    org_chart_prdmgr.name AS prdmgr_name,
    org_chart_prdmgr.code AS prdmgr_code,
    part_regional.part_num,
    part_regional.code,
    part_regional.long_ptno,
    part_regional.projcst,
    part_regional.prod_cd5,
    part_regional.cr_dt,
    part_regional.shrt_desc,
    part_regional.long_desc,
    part_regional.fran_code,
    part_regional.prtcls,
    part_regional.sup_prt,
    part_regional.prtstat,
    part_regional.popcdny,
    part_regional.popcdcy,
    part_regional.pllqty,
    part_regional.drop_ship,
    part_regional.cat_cd,
    part_regional.cc1,
    part_regional.cc2,
    part_regional.cc3,
    part_regional.cc4,
    part_regional.cc5,
    part_regional.sac,
    part_regional.uac,
    part_regional.stdcst,
    part_regional.crcst,
    part_regional.lprc,
    part_regional.crprc,
    part_regional.stdmcrcst,
    part_regional.lpp_prc,
    part_regional.lppqty,
    part_regional.lppdt,
    part_regional.lppvndr,
    part_regional.postdt,
    part_regional.poenddt,
    part_regional.povndr,
    part_regional.pofgt,
    part_regional.popblp,
    part_regional.popblq,
    part_regional.popt,
    part_regional.pocurr,
    part_regional.pofdc,
    part_regional.uytd,
    part_regional.uy1qty,
    part_regional.uy2qty,
    part_regional.uy3qty,
    part_regional.uy4qty,
    part_regional.uy5qty,
    part_regional.mfgnr,
    part_regional.mfgcommcd,
    part_regional.mfgfamcd,
    part_regional.pnf_fmsi,
    part_regional.mktcdl1,
    part_regional.mktcdl2,
    part_regional.mktcdl3,
    part_regional.mktcdl4,
    part_regional.mktcdl5,
    part_regional.kit_flag,
    part_regional.cr_gp,
    part_regional.core_part,
    part_regional.origin,
    part_regional.nonrtn,
    part_regional.harcode,
    part_regional.ldtime,
    part_regional.upc,
    part_regional.vmrs,
    part_regional.height,
    part_regional.prtlen,
    part_regional.prtwid,
    part_regional.planner,
    part_regional.buyer,
    part_regional.cystdmtl,
    part_regional.dutfrgexc,
    part_regional.dutycst,
    part_regional.frgtcst,
    part_regional.mfglabcst,
    part_regional.whburcst,
    part_regional.mfgbcst,
    part_regional.warbcst,
    part_regional.pckcst,
    part_regional.corqty,
    part_regional.vndrnm,
    part_regional.vndrcd,
    p_pricing_region_rgcd.id AS rgcd,
    p_pricing_region_rgcd.name AS rgcd_name,
    p_pricing_region_rgcd.code AS rgcd_code,
    x_sub_brand_sub_brand.id AS sub_brand,
    x_sub_brand_sub_brand.name AS sub_brand_name,
    x_sub_brand_sub_brand.code AS sub_brand_code,
    part_regional.part_uofm,
    part_regional.rg_part,
    part_regional.cbseg,
    part_regional.sup_dt,
    part_regional.id,
    part_regional.updated_by,
    part_regional.updated_date,
    part_regional.validationstatus,
    part_regional.is_valid,
    part_regional.created_date,
    part_regional.created_by,
    part_regional.comment
   FROM ((((((((((part_regional part_regional
     LEFT JOIN x_mfg_prod_code_class x_mfg_prod_code_class_mfgcc ON ((part_regional.mfgcc = x_mfg_prod_code_class_mfgcc.id)))
     LEFT JOIN x_product_code_1_digit x_product_code_1_digit_prod_cd1 ON ((part_regional.prod_cd1 = x_product_code_1_digit_prod_cd1.id)))
     LEFT JOIN x_good_better_best x_good_better_best_gbb ON ((part_regional.gbb = x_good_better_best_gbb.id)))
     LEFT JOIN p_pricing_region p_pricing_region_rgcd ON ((part_regional.rgcd = p_pricing_region_rgcd.id)))
     LEFT JOIN x_product_code_3_digit x_product_code_3_digit_prod_cd3 ON ((part_regional.prod_cd3 = x_product_code_3_digit_prod_cd3.id)))
     LEFT JOIN org_chart org_chart_prdmgr ON ((part_regional.prdmgr = org_chart_prdmgr.id)))
     LEFT JOIN x_mfg_prod_code x_mfg_prod_code_mfgpdcd ON ((part_regional.mfgpdcd = x_mfg_prod_code_mfgpdcd.id)))
     LEFT JOIN x_lifecycle_stage x_lifecycle_stage_lfcycle ON ((part_regional.lfcycle = x_lifecycle_stage_lfcycle.id)))
     LEFT JOIN x_brand x_brand_brnd_cd ON ((part_regional.brnd_cd = x_brand_brnd_cd.id)))
     LEFT JOIN x_sub_brand x_sub_brand_sub_brand ON ((part_regional.sub_brand = x_sub_brand_sub_brand.id)));;

ALTER TABLE public.view_part_regional
    OWNER TO postgres;