-- View: public.view_sro_groups

-- DROP VIEW public.view_sro_groups;

CREATE OR REPLACE VIEW public.view_sro_groups AS
SELECT sro_groups.code,
    sro_groups.name,
    x_sro_group_name_sro_gname.id AS sro_gname,
    x_sro_group_name_sro_gname.name AS sro_gname_name,
    x_sro_group_name_sro_gname.code AS sro_gname_code,
    sro_groups.apart,
    sro_groups.apartsale,
    sro_groups.app,
    sro_groups.brakesz,
    sro_groups.bushtype,
    sro_groups.flngdm,
    sro_groups.indnum,
    sro_groups.ltapdm,
    sro_groups.loorunlo,
    sro_groups.oem,
    sro_groups.roddm,
    sro_groups.stapdm,
    sro_groups.sctre,
    sro_groups.sthrddm,
    sro_groups.style,
    sro_groups.taplen,
    sro_groups.tubtype,
    sro_groups.type,
    sro_groups.nospline,
    sro_groups.beardm,
    sro_groups.series,
    sro_groups.splen,
    sro_groups.tubodm,
    sro_groups.ewalltk,
    sro_groups.crosslen,
    sro_groups.ykdim,
    sro_groups.axleapp,
    sro_groups.axleser,
    sro_groups.bpw,
    sro_groups.bcd,
    sro_groups.bhd,
    sro_groups.brtype,
    sro_groups.efflen,
    sro_groups.fmsi,
    sro_groups.grade,
    sro_groups.headsty,
    sro_groups.hubsty,
    sro_groups.hubtype,
    sro_groups.kpdm,
    sro_groups.kplen,
    sro_groups.kptype,
    sro_groups.lorr,
    sro_groups.len,
    sro_groups.model,
    sro_groups.norrem,
    sro_groups.oeman,
    sro_groups.ratio,
    sro_groups.type1,
    sro_groups.ydimae,
    sro_groups.chmbrty,
    sro_groups.cssc,
    sro_groups.headty,
    sro_groups.ssc,
    sro_groups.spldm,
    sro_groups.hubcaps,
    sro_groups.noaxles,
    sro_groups.singletr,
    sro_groups.axlemod,
    sro_groups.spintype,
    sro_groups.ctype,
    sro_groups.oasslen,
    sro_groups.conntype,
    sro_groups.indm,
    sro_groups.sysconfg,
    sro_groups.isdm,
    sro_groups.clutch,
    sro_groups.torque,
    sro_groups.bore,
    sro_groups.convst,
    sro_groups.ptype,
    sro_groups.compty,
    sro_groups.sc4thick,
    sro_groups.bodydm,
    sro_groups.colllen,
    sro_groups.exlen,
    sro_groups.cte,
    sro_groups.collst,
    sro_groups.toolt,
    sro_groups.frictmix,
    sro_groups."position",
    sro_groups.ctelen,
    sro_groups.sensor,
    sro_groups.gawr,
    sro_groups.class,
    sro_groups.lrank,
    sro_groups.brand,
    sro_groups.genafter,
    sro_groups.trotor,
    sro_groups.teeth,
    sro_groups.odm,
    sro_groups.odmmm,
    x_yes_no_flag_maingrp.id AS maingrp,
    x_yes_no_flag_maingrp.name AS maingrp_name,
    x_yes_no_flag_maingrp.code AS maingrp_code,
    sro_attributes_srocat.id AS srocat,
    sro_attributes_srocat.name AS srocat_name,
    sro_attributes_srocat.code AS srocat_code,
    sro_groups.leader,
    sro_groups.family,
    sro_groups.vndr,
    sro_groups.caltype,
    sro_groups.pcode5,
    sro_groups.part_num,
    sro_groups.trkcode,
    sro_groups.id,
    sro_groups.updated_by,
    sro_groups.updated_date,
    sro_groups.validationstatus,
    sro_groups.is_valid,
    sro_groups.created_date,
    sro_groups.created_by,
    sro_groups.comment
   FROM (((sro_groups sro_groups
     LEFT JOIN x_sro_group_name x_sro_group_name_sro_gname ON ((sro_groups.sro_gname = x_sro_group_name_sro_gname.id)))
     LEFT JOIN sro_attributes sro_attributes_srocat ON ((sro_groups.srocat = sro_attributes_srocat.id)))
     LEFT JOIN x_yes_no_flag x_yes_no_flag_maingrp ON ((sro_groups.maingrp = x_yes_no_flag_maingrp.id)));;

ALTER TABLE public.view_sro_groups
    OWNER TO postgres;